version: "3.5"

services:
  web:
    image: bref/fpm-dev-gateway
    ports:
      - '8000:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/var/task
      - ./docker/php/xdebug.ini:/opt/bref/etc/php/conf.d/php.ini
    env_file:
      - .env