version: "3.5"

services:
  web:
    image: bref/fpm-dev-gateway
    ports:
      - '8000:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/var/task
      - ./docker/php/xdebug.ini:/opt/bref/etc/php/conf.d/xdebug.ini
    env_file:
      - .env

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root